server:
  port: 8899  #????????
spring:
  redis:
    port: 6379 #Redis??????
    host: localhost # Redis???IP??
    database: 0 #??16???????
  datasource:
#      url: jdbc:mysql://localhost:3306/security?useSSl=false&userUniCode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        url: jdbc:mysql://localhost:3306/security?useSSl=false&userUniCode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
        username: root
        password: 123456
        min-idle: 10
        max-active: 30
        driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyy-MM-dd HH:mm:ss.SSS #???????

# MybatisPlus ????
mybatis-plus:
  type-aliases-package: com.hzlx.entity #???????
  mapper-locations: classpath*:/mapper/**/*Mapper.xml #Mapper.xml ??????
  configuration:
    map-underscore-to-camel-case: true #????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??????
  global-config:
    db-config:
      logic-delete-field: status #???????
      logic-not-delete-value: 1 #??????
      logic-delete-value: 0 #??????


pagehelper:
  #?????????
  # 3.3.0???? - ??????????false???
  #?????????pageNum<1?????????pageNum>pages???????
  #?????????pageNum<1?????????pageNum>pages???????
  reasonable: true
  support-methods-arguments: true
  # ???true????pageSize=0??RowBounds.limit = 0??????????
  #??????????????????????Page???
  page-size-zero: true
  #3.5.0???? - ????startPage(Object params)??
  #?????`params`?????????????Map?ServletRequest???
  # ????pageNum,pageSize,count,pageSizeZero,reasonable,??????????
  # ????????????????????
  params: count=countSql


my-config:
  exclude:
    paths:
      # ?????????
      anonymous: /user/login
      # ????????
      permit: /test/test
  redis-key: "user:"
  token-key: token